name: Build medonetRSS feed

on:
  schedule:
    # Uwaga: CRON w UTC. Dla 13:00 i 20:00 czasu Warszawy obecnie ~11:00 i ~18:00 UTC (CEST).
    - cron: "0 11 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS
        run: |
          python scripts/aggregate_medonet.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/medonet.xml
          git commit -m "Update medonet.xml [skip ci]" || echo "No changes to commit"
          git push
